### ISSUE TITLE
is not in the SourceMap error

### ISSUE THREAD

**Issue by kilianc** [scniro/gulp-clean-css#1]
```
/some/path/website/node_modules/source-map/lib/source-map-consumer.js:703
        throw new Error('"' + aSource + '" is not in the SourceMap.');
        ^

Error: "/node_modules/bourbon-neat/app/assets/stylesheets/grid/_box-sizing.scss" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/some/path/website/node_modules/source-map/lib/source-map-consumer.js:703:15)
    at SourceMapGenerator.<anonymous> (/some/path/website/node_modules/source-map/lib/source-map-generator.js:229:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/some/path/website/node_modules/source-map/lib/source-map-generator.js:228:34)
    at applySourceMap (/some/path/website/node_modules/vinyl-sourcemaps-apply/index.js:27:15)
    at /some/path/website/node_modules/gulp-clean-css/index.js:65:25
    at whenSourceMapReady (/some/path/website/node_modules/clean-css/lib/clean.js:139:16)
    at /some/path/website/node_modules/clean-css/lib/clean.js:151:18
    at fromString (/some/path/website/node_modules/clean-css/lib/utils/input-source-map-tracker.js:33:10)
    at InputSourceMapStore.track (/some/path/website/node_modules/clean-css/lib/utils/input-source-map-tracker.js:236:5)
```

**Comment by scniro** [comment]
@kilianc Thanks for opening this up. I can't quite tell whats going on here from your trace, could you post the gulp task so I can try to repro later today?

**Comment by kilianc** [comment]
```js

gulp.task('css', () => {
  return gulp.src('app/css/main.scss')
    .pipe(plugins.rename('bundle.min.css'))
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass({
      includePaths: ['styles'].concat(neat)
    }))
      .on('error', plugins.sass.logError)
    .pipe(plugins.postcss([
      require('postcss-assets')({
        loadPaths: ['images'],
        basePath: 'app',
        relative: true
      })
    ]))
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest('app'))
})

gulp.task('minify:css', () => {
  return gulp.src('app/bundle.min.css')
    .pipe(plugins.sourcemaps.init({ loadMaps: true }))
    .pipe(plugins.cleanCss())
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest('dist'))
})
```

**Comment by scniro** [comment]
@kilianc  Looks like you are `write`-ing your sourcemaps twice. When I've used sourcemaps in a less environment, I initially `init()`, then `init({ loadMaps: true })` as you have already, then do a final `write`. Was this working before and an update to the plugin now broke this?

**Comment by kilianc** [comment]
@scniro I write them twice because that's the desired behavior:

- first pass: compile all css for development and offer a sourcemap for easy debug
- second pass: create production ready file and offer a sourcemap for easy debug :D

I never used clean-css before so I don't know what's breaking

**Comment by scniro** [comment]
@kilianc okay sounds good, hm, if you don't mind I'm going to ask a few more questions and request some scenarious just because I am unsure what piece is broken here.

Does the first pass alone work?

Do your tasks run without generating sourcemaps?

**Comment by kilianc** [comment]
yes and yes.

**Comment by scniro** [comment]
@kilianc  Looking at the stack trace again, it's looking for a `.scss` file sourcemap but in regards to `.css` files. Perhaps this is an issue? Also, in your second task, you appear to glob a `.min.css` file. Is this file already minified? Try removing `loadMaps: true` in your second task and check the outcome. Sorry if my explanations suck, I'm trying to debug this with you because there is a chance it's not an issue with the plugin itself. I'm going to write tests for the `gulp-sourcemaps` integration, but my initial looks on it indicate it's working as expected

**Comment by kilianc** [comment]
Why don't I create a failing test case? I have a feeling I'll be posting this issue around on multiple repos :D

**Comment by scniro** [comment]
@kilianc perfect!! :D I have a similar feeling on that as well, but I'll in the least try to help you resolve it, even if it's not due to this plugin directly

**Comment by scniro** [comment]
@kilianc if you care to check it out or pull the repo, I added some test cases regarding sourcemap support. I didn't use your exact plugins regarding your sass build, but I added a case for two passes on sourcemaps and it appears to work as intended. Were you able to make any more discoveries with this?

**Comment by kilianc** [comment]
Had a busy day but I'll try to patch up a test case before going to sleep. And btw thanks a lot for the help!

**Comment by scniro** [comment]
@kilianc did you get a chance to look into this further?

**Comment by kilianc** [comment]
@scniro see https://github.com/floridoo/vinyl-sourcemaps-apply/issues/11 and https://github.com/ben-eb/gulp-cssnano/issues/38

**Comment by arechsteiner** [comment]
@scniro: I'm experiencing this bug and I have created a minimal project to reproduce it:

https://github.com/arechsteiner/cleancss-bug

In my case, the bug is caused by importing  a SCSS file from a third-party npm package like so:

    @import "../node_modules/bootstrap/scss/mixins/_breakpoints.scss";
    @import "../node_modules/bootstrap/scss/_variables.scss";

**Comment by joaocunha** [comment]
@scniro my case follows @arechsteiner's. 

```
// Compile SCSS
gulp.task("sass", () =>
  gulp.src("./src/scss/main.scss")
    .pipe(plumber({
      errorHandler: notify.onError("Sucky SCSS! <%= error.message %>")
    }))
    .pipe(sourcemaps.init())
    .pipe(sass({
      includePaths: require("node-normalize-scss").includePaths, // WORKS FINE WITH NORMALIZE
      includePaths: require("bourbon-neat").includePaths // BREAKS WITH NEAT
    }))
    .pipe(colorguard())
    .pipe(autoprefixer())
    .pipe(sourcemaps.write("./"))
    .pipe(gulp.dest("./dist/css"))
    .pipe(cleanCSS({compatibility: "ie8"}))
    .pipe(rename("./dist/css/main.min.css"))
    .pipe(sourcemaps.write("./"))
    .pipe(gulp.dest(""))
    .pipe(browserSync.stream())
);
```

**Comment by scniro** [comment]
@joaocunha @arechsteiner hey guys thanks for supplying some more info on this one. I've been so unusually busy lately and haven't been as attentive as I'd like looking into these things. Hopefully I'll get a chance to do so very soon! I'll keep you all posted if I find anything. Thanks for understanding

**Comment by dcwarwick** [comment]
+1 for @arechsteiner 's scenario. I have the same thing: if I import a .scss file from a package in my node_modules into my project's main .scss file, and that imported .scss file itself contains @imports of other .scss files within that package, then the sass compile works fine and the sourcemaps appears to work fine but cleancss gives the "not in the Sourcemap" error. I started trying to debug but haven't got very far yet...

**Comment by dcwarwick** [comment]
OK, this might help: it seems that it is any time a sass import has one or more ```../``` at the start of the path. Those ```../``` seem to be getting lost. Example:

If I put a file ```_foo.scss```, and then make a subdirectory ```sub``` in which I put a file ```bar.scss```, and in ```bar.scss``` I have
```
  @import '../foo';
```
and in my gulp build I pipe ```bar.scss``` to ```sourcemaps()```, then to ```sass()```, then to ```cleancss()```, it will give this error:
```
  Error: "/foo.scss" is not in the SourceMap.
```
Notice that the path here, ```/foo.scss```, seem to have lost the ```../``` from the start.

I hope this helps.

**Comment by scniro** [comment]
Okay guys I've dug into this a little bit this morning. A bit tricky to pin the blame here, but I think it can be traced back to [gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps). I found [this issue](https://github.com/floridoo/gulp-sourcemaps/issues/108) which seems to complain of encountering the same problem, which led me down the path of exploring [write-options](https://github.com/floridoo/gulp-sourcemaps#write-options) - which has a `sourceRoot` option. Playing with this, I modified the gulp task as such...

    gulp.task('default', function() {
        return gulp .src('scss/**/*.scss')
            .pipe(sourcemaps.init())
            .pipe(sass().on('error', sass.logError))
            .pipe(sourcemaps.write({includeContent: false, sourceRoot: './scss'}))
             .pipe(gulp.dest('dist/css/'))
             .pipe(sourcemaps.init({loadMaps: true}))
             .pipe(cleanCss())
             .pipe(sourcemaps.write())
             .pipe(gulp.dest('dist/css/min/'));
    });

After implementing this, the error goes away and all _seems_ to work as expected. I [forked the error reproduction](https://github.com/scniro/cleancss-bug) project supplied by @arechsteiner with the modified task and added a small express server file to glue everything together in the browser, and I can see the styles with the mapping. Can someone check this out when they get time and share your thoughts on if this seems sensible? Thanks all!

**Comment by dcwarwick** [comment]
Good catch @scniro. What this actually comes down to is that the error does not occur if ```includeContent:false``` is used. I would guess that it is when sourcemaps attempts to load up the original content to include it in the map that the error occurs. This is a useful partial workaround --- partial, because with ```includeContent:false``` the source files will need to be available (served) when debugging, which isn't always possible/desirable. But this may also help in tracking down where the problem is happening.

**Comment by gregbrown1229** [comment]
@dcwarwick @scniro 

I had a problem similar to this today, and after much research, I found it was an issue with gulp-sourcemaps concerning the 'sourceRoot' property. Version 2.0.0-alpha of gulp-sourcemaps has a fix, but in order to use 1.6.0 (the current stable release), your call to the .write() method should look like this:

`.pipe(sourcemaps.write(undefined, {
sourceRoot: null
}))`

Hope this helps!

**Comment by scniro** [comment]
> `.pipe(sourcemaps.write(undefined, { sourceRoot: null }))`

gross!! @gregbrown1229 so has that proved to be a viable workaround for now? Sorry I don't have a straightforward solution to this one guys, looks like we're at the crux of gulp-sourcemaps while in this predicament.

**Comment by joaocunha** [comment]
Also, how a path would fit in that `.write()` call?

**Comment by gregbrown1229** [comment]
@scniro It works for my purposes at the moment, anyway. Can't say whether it works for all use cases, though.

@joaocunha For me, calling `sourcemaps.write('./maps')` works without issue. It's only when I'm trying to write the sourcemap directly to the CSS file that I run into this issue.

**Comment by joaocunha** [comment]
@gregbrown1229 weird. I run into issues with a path (`.pipe(sourcemaps.write("./"))`).

**Comment by gregbrown1229** [comment]
@joaocunha I'm taking the day off just to code for fun, so I grabbed your gulp task from your initial post, added in the mods that @scniro mentioned, then added `{sourceRoot: null}` to the first sourcemaps.write() call, and it seemed to work! (At least in my test project.)

```javascript
// Compile SCSS
gulp.task('sass', () =>
  gulp.src('./src/main.scss')
    .pipe(plumber({
		errorHandler: notify.onError('Sucky SCSS! <%= error.message %>')
    }))
    .pipe(sourcemaps.init())
    .pipe(sass({
    	includePaths: [normalizePaths, neatPaths, bourbonPaths] // Replace these with whatever you need, obviously
    }))
    .pipe(colorguard())
    .pipe(autoprefixer())
    .pipe(sourcemaps.write('./', {sourceRoot: null}))
	.pipe(sourcemaps.init({loadMaps: true}))
    .pipe(gulp.dest('./dist/css'))
    .pipe(cleanCSS({compatibility: 'ie8'}))
    .pipe(rename('./dist/css/main.min.css'))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest(''))
    .pipe(browserSync.stream())
);
```

**Comment by dcwarwick** [comment]
Thanks @gregbrown1229 for the pointers here. I can confirm that doing a first ```sourcemaps.write()``` with ```sourceRoot: null``` avoids the errors, and I've done a little digging to figure out why.

The problem seems to stem from these lines in ```gulp-sourcemap``` file ```index.js``` (lines 190-194 in the source I was looking at):
```
      if (sourceMap.sourceRoot === undefined) {
        sourceMap.sourceRoot = '/source/';
      } else if (sourceMap.sourceRoot === null) {
        sourceMap.sourceRoot = undefined;
      }
```

These cause all paths to be evaluated relative to a fictitious ```/source/``` root if no explicit ```sourceRoot``` was specified. However, this means that paths with sufficient ```../``` at the start to take the path *above* the path of the main SCSS file will lose those initial ```../``` during resolution of the relative paths, and this will cause the error to occur when the source needs to be loaded. A ```sourceRoot``` expliticly set to ```null```, as you can see above, causes it to be set to ```undefined```, and all paths are then resolved relative to the current working directory, so as long as there aren't sufficient ```../``` at the start of a path to take it out of the current working directory everything will now be hunky-dory.

Unfortunately, there doesn't seem to be a way to directly set the ```sourceRoot```: the option only exists on ```write()```. This means that in order to use this workaround, a ```write()``` must be done, with ```sourceRoot: null```, followed by an ```init``` with ```loadMaps: true```, prior to carrying out the ```cleancss()```.

I can also confirm that using ```gulp-sourcemaps``` 2.0.0-alpha avoids the errors too. This is because in this version of ```gulp-sourcemaps``` the assigning of ```/source/``` to an undefined ```sourceRoot``` is NOT done.

I have not figured out why ```cleancss()``` triggers this error while other plugins in the pipeline don't -- it's presumably something to do with exactly what ```cleancss()``` does. But I think @scniro is right: it's basically a ```gulp-sourcemaps``` problem, and will go away when ```gulp-sourcemaps``` makes it to v2. In the mean time, doing a ```write()``` with ```sourceRoot: null``` followed by an ```init``` with ```loadMaps: true```, prior to carrying out the ```cleancss()```, is a workaround.

**Comment by gregbrown1229** [comment]
@dcwarwick I don't think the issue is isolated to (or perhaps even related to--I'm not sure) `cleancss()`, since I ran into this issue never having used it.  In fact, I only installed it to test my solution for @joaocunha's problem. I just happened upon this issue after googling for the error message I was encountering. It seems like it has to do with the combination of `includePaths` in the gulp-sass call and `gulp-sourcemaps`, but I only dug far enough to find a workaround, since I found that `gulp-sourcemaps` already has a solution in their upcoming release.

**Comment by scniro** [comment]
@kilianc @arechsteiner @joaocunha @dcwarwick @gregbrown1229 ...

Hey there! So, I'm playing with some new stuff for a new version to publish, but I'm not heavy enough of a sourcemap user to really get down to the nitty gritty with the issues yourselves and others are experiencing. I'm trying to make the plugin less opinionated with sourcemaps, and letting clean-css under the hood take care of all the mapping.

My initial runs with it seem okay, but I'm wanting some more feedback before I'm confident to publish a new version. I made a new repo with a packaged version, [gulp-clean-css-test](https://github.com/scniro/gulp-clean-css-test). If you'd be willing, please clone this and install the packaged plugin into your project via `npm install ../path/to/this/repo/gulp-clean-css-2.1.0.tgz` and share any results you may have?

Also, if you're a command liner user of clean-css, can you compare the results of that with the plugin? If not, no worries. I am aiming for identical output so any sourcemapping issues aren't attributed to the specifics of this wrapper.

**Comment by scniro** [comment]
Check out [npm 2.1.0](https://www.npmjs.com/package/gulp-clean-css) and feel free to share your findings on here if it's now resolved

**Comment by scniro** [comment]
@kilianc @arechsteiner @joaocunha @dcwarwick @gregbrown1229  whirlwind of stuff yesterday, try 2.1.3 please

**Comment by scniro** [comment]
more whirlwind => 2.2.0
