### ISSUE TITLE
latest releases aren't shown on npm

### ISSUE THREAD

**Issue by cordoval** [scniro/gulp-clean-css#10]
"1.2.4 is the latest of 40 releases" which is not true

**Comment by scniro** [comment]
@cordoval  Unsure what you mean, I'm looking at [gulp-clean-css on npm](https://www.npmjs.com/package/gulp-clean-css) and see it as current...

 > 2.0.12 is the latest of 16 releases

Can you clarify where you are seeing the details you shared?

Maybe you're looking at the [old gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css) plugin? I assumed the transition to the new gulp-clean-css plugin was pretty straightforward, since the gulp-minify-css plugin has a verbose deprecation message.

 > deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
