### ISSUE TITLE
calc () issue

### ISSUE THREAD

**Issue by al5dy** [scniro/gulp-clean-css#48]
gulp-clean-css v.3.7.0

The following code does not work correctly  in SASS mixin e.g:

```
@mixin angle-edge ($angle){
$angle-calc-top: calc(0% + #{$angle}vw); // bug here 0%

$clip-path-top: 0 $angle-calc-top, 100% 0;
$clip-path-bottom: 100% 100%, 0 100%;

 $clip-path: polygon($clip-path-top, $clip-path-bottom);
  clip-path: $clip-path;
}
```

```
.angle--top-left {
  @include angle-edge($angle: 2);
}
```

Output as:

.angle--top-left {
polygon(0 calc(**0** + 2vw),100% 0,100% 100%,0 100%); /* 0 */
}

instead of

.angle--top-left {
polygon(0 calc(**0%** + 2vw),100% 0,100% 100%,0 100%); /* 0% */
}

p.s
Temporary solution used 0.1% instead of 0%

**Comment by scniro** [comment]
Unfortunately this cannot be fixed with the wrapper as your issue is either stemming from [clean-css](https://github.com/jakubpawlowicz/clean-css) or [node-sass](https://github.com/sass/node-sass). 

Possibly related, today I released [gulp-clean-css 3.8.0](https://github.com/scniro/gulp-clean-css/releases/tag/3.8.0) which includes the [4.1.8 release of clean-css](https://github.com/jakubpawlowicz/clean-css/releases/tag/v4.1.8). Updating could possibly fix your issue. If it does not however, you'll need to follow up with the above mentioned libs.
