### ISSUE TITLE
How to prevent rebase of images in css?

### ISSUE THREAD

**Issue by phackwer** [scniro/gulp-clean-css#62]
I'm facing the following problem:

We have a big angular project with a lot of lazy loading, including CSS for each module. When gulp-clean-css is executed, it adds a crazy path to the images. We want to prevent it without having to edit all the CSS (it's a log) to set absolute positioning.

How can I prevent clean-css to rebase my images using gulp-clean-css?

**Comment by scniro** [comment]
@phackwer thank you for the interest, but I'd recommend asking a question on [StackOverflow](https://stackoverflow.com/). If you include an isolated working example you'll surely get an answer the same day. Closing for now as I'm not sure the solution lies within modifying the repo itself, but please reopen should you suspect otherwise.
